language: python
#python:
#  - "2.7" disable 2.7 for now
#  - "3.6"
# Current workaround to enable 3.7 without globally enabling
# sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - python setup.py install
script:
  - pytest
  - pylint two_qubit_simulator --rcfile=.pylintrc
